-- One-time schema update for an existing MySQL database. Existing rows should be APPROVED.
ALTER TABLE `Property` ADD COLUMN `status` VARCHAR(191) NOT NULL DEFAULT 'APPROVED';
ALTER TABLE `Room` ADD COLUMN `status` VARCHAR(191) NOT NULL DEFAULT 'APPROVED';
ALTER TABLE `Package` ADD COLUMN `status` VARCHAR(191) NOT NULL DEFAULT 'APPROVED';
ALTER TABLE `Event` ADD COLUMN `status` VARCHAR(191) NOT NULL DEFAULT 'APPROVED';
