'use client';
import { useEffect, useState } from 'react';
const statusStyle = (status: string) => ({ display: 'inline-block', padding: '4px 9px', borderRadius: 999, fontSize: 12, fontWeight: 700, background: status === 'PENDING' ? '#fff7ed' : '#fef2f2', color: status === 'PENDING' ? '#c2410c' : '#b91c1c' });
export default function SuperAdmin() {
  const [data, setData] = useState<any>({ properties: [], rooms: [], events: [], packages: [], counts: {} }); const [loading, setLoading] = useState(true); const [message, setMessage] = useState('');
  async function load() { setLoading(true); const r = await fetch('/api/superadmin/requests', { cache: 'no-store' }); if (r.status === 401) { window.location.href = '/superadmin/login'; return; } setData(await r.json()); setLoading(false); }
  useEffect(() => { load(); }, []);
  async function review(type: string, id: string, action: 'approve'|'reject', propertyId?: string) { const r = await fetch('/api/superadmin/requests/review', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ type, id, propertyId, action }) }); const d = await r.json(); if (!r.ok) { setMessage(d.error || 'Could not update request'); return; } setMessage(action === 'approve' ? 'Approved successfully. It can now appear on the website.' : 'Request rejected.'); load(); }
  async function logout() { await fetch('/api/superadmin/logout', { method: 'POST' }); window.location.href = '/superadmin/login'; }
  const cards = [['Properties', data.counts.properties || 0], ['Rooms', data.counts.rooms || 0], ['Events', data.counts.events || 0], ['Packages', data.counts.packages || 0]];
  const rooms = data.rooms || [];
  return <main className="admin-shell"><aside className="admin-sidebar"><div className="admin-brand-wrap"><img src="/sawariya-logo.jpeg" className="admin-logo" alt="Sawariya Event"/></div><div className="admin-label">SUPERADMIN</div><nav className="admin-nav"><button className="active"><span className="nav-dot"/>Approval Requests</button><button onClick={load}><span className="nav-dot"/>Refresh</button></nav><button className="admin-site-link" onClick={logout}>Logout</button></aside><section className="admin-main"><header className="admin-topbar"><div><p className="admin-kicker">SAWARIYA EVENT</p><h1>Approval Center</h1></div><div className="admin-user"><span className="admin-avatar">S</span><div><strong>Superadmin</strong><small>Content Approval</small></div></div></header>{message && <div className="admin-toast">{message}<button onClick={() => setMessage('')}>×</button></div>}<section className="admin-panel"><div className="panel-head"><div><p className="admin-kicker">PENDING CONTENT</p><h2>Requests waiting for approval</h2></div><button className="admin-primary" onClick={load}>↻ Refresh</button></div><div className="admin-stats">{cards.map(([label, value]) => <div className="stat-card" key={String(label)}><span>{label}</span><strong>{value}</strong></div>)}</div>{loading ? <p className="admin-muted">Loading requests…</p> : !data.counts.properties && !data.counts.events && !data.counts.packages && !data.counts.rooms ? <p className="admin-muted">No pending requests. Everything is reviewed.</p> : <><RequestGroup title="Properties" items={data.properties} type="property" review={review}/><RequestGroup title="Rooms" items={rooms} type="room" review={review}/><RequestGroup title="Events" items={data.events} type="event" review={review}/><RequestGroup title="Packages" items={data.packages} type="package" review={review}/></>}</section></section></main>;
}
function RequestGroup({ title, items, type, review }: { title: string; items: any[]; type: string; review: Function }) { if (!items.length) return null; return <div style={{ marginTop: 28 }}><div className="panel-head"><h3>{title}</h3><span style={statusStyle('PENDING')}>{items.length} pending</span></div><div className="admin-list">{items.map((item: any) => <div className="admin-list-row" key={`${type}-${item.propertyId || ''}-${item.id}`}><img src={item.image || '/sawariya-logo.jpeg'} alt=""/><div><strong>{item.title || item.name}</strong><small>{(item.propertyName || item.property?.name) ? `Property: ${item.propertyName || item.property?.name} · ` : ''}{item.location || item.kicker || item.description || item.size || ''}</small><span style={statusStyle(item.status || 'PENDING')}>{item.status || 'PENDING'}</span></div><div className="row-actions"><button className="admin-edit" onClick={() => review(type, item.id, 'approve', item.propertyId)}>Approve</button><button className="admin-danger" onClick={() => review(type, item.id, 'reject', item.propertyId)}>Reject</button></div></div>)}</div></div>; }
